### ISSUE TITLE
Only works where fs is available.

### ISSUE THREAD

**Issue by aesopwolf** [fmarcia/UglifyCSS#47]
I'm using UglifyCSS in a browser environment (via webpack), but I had to fork it and remove all `fs` references. (https://github.com/aesopwolf/UglifyCSS)

What are your thoughts on breaking this project out into multiple parts? Or even just breaking up the  `uglifycss-lib.js` file so the `fs` import is only in a file for the `processFiles` method?

**Comment by fmarcia** [comment]
Thanks for your feedback.

Using uglifycss in a browser environment needs more than excluding fs module in uglifycss-lib.js. The path module is required, the module object is used without checking its avaibility. Besides, it should be amd and import friendly as well.

Isn't there a way to pre-process css files with webpack, instead of doing it at run time for every request?

Anyway, it represents too much time and I don't plan to maintain a browser version of the library. Sorry for that.

**Comment by gloony** [comment]
I need it so I make a port.
https://gist.github.com/gloony/8418bb03985f217948f97db7291a15b5

Usage
`var output = UglifyCSS.processString(input);`
