### ISSUE TITLE
@supports syntax is made invalid after uglifying

### ISSUE THREAD

**Issue by xfinx** [fmarcia/UglifyCSS#52]
I have a file which contains the following css:
@supports ((-webkit-clip-path: polygon(0 0, 0 0, 0 0)) or (clip-path: polygon(0 0, 0 0, 0 0))) {
...

after I've run this through uglifycss the following output is created:
@supports((-webkit-clip-path:polygon(0 0,0 0,0 0)) or(clip-path:polygon(0 0,0 0,0 0))){

version:
└─┬ gulp-uglifycss@1.0.8
  └── uglifycss@0.0.25

**Comment by fmarcia** [comment]
Thanks for your report.
I tried to use the output you provided in Firefox and it worked fine. Could you be more specific?

**Comment by fmarcia** [comment]
No feedback

**Comment by schjetne** [comment]
This bug should be reopened. Missing whitespace after `or` breaks the `@supports` rule in latest Chrome.

In my case, I was scratching my head because my `position: sticky` didn't work in Chrome, until I realized `@supports((position: sticky) or (-webkit-position: sticky))` had been turned into `@supports((position: sticky) or(-webkit-position: sticky))`. I manually inserted the missing space and the rule worked as intended.

**Comment by arkhi** [comment]
This is also the case with at least Firefox 68.0.2 and Chrome 6.0.3809.132.

**Comment by arkhi** [comment]
The bug can be seen here: https://jsfiddle.net/te1sk5a6/.

Just add the space on the second @ rule and the text should turn blue.

**Comment by arkhi** [comment]
The CSS Specifications specify that conjunction and disjunction tokens should have a space around:

- https://www.w3.org/TR/css3-mediaqueries/#error-handling, example 20
- https://www.w3.org/TR/css3-conditional/#or
